BEGIN TRANSACTION;
insert into EventComments (EventId, UserId, Content) values (72, 101, 'Hodg lymph-histio axilla');
insert into EventComments (EventId, UserId, Content) values (58, 33, 'Syphilitic aortic valve');
insert into EventComments (EventId, UserId, Content) values (42, 93, 'Lte ef-mplga low lmb NOS');
insert into EventComments (EventId, UserId, Content) values (61, 79, 'TB bronchiectasis-unspec');
insert into EventComments (EventId, UserId, Content) values (73, 24, 'Cndct dsrdr adlscnt onst');
insert into EventComments (EventId, UserId, Content) values (23, 46, 'Dentl caries-smooth surf');
insert into EventComments (EventId, UserId, Content) values (80, 33, 'Vertebral fx NOS-closed');
insert into EventComments (EventId, UserId, Content) values (11, 14, 'Hallucinogen dep-episod');
insert into EventComments (EventId, UserId, Content) values (93, 65, 'Dialysis encounter, NEC');
insert into EventComments (EventId, UserId, Content) values (23, 62, 'Concus-brief coma <31 mn');
insert into EventComments (EventId, UserId, Content) values (1, 24, 'Adv eff antineoplastic');
insert into EventComments (EventId, UserId, Content) values (41, 8, 'Accommodative esotropia');
insert into EventComments (EventId, UserId, Content) values (63, 69, 'Hypercalcemia');
insert into EventComments (EventId, UserId, Content) values (42, 12, 'Mild dysplasia of cervix');
insert into EventComments (EventId, UserId, Content) values (8, 16, 'Ac supp OM w drum rupt');
insert into EventComments (EventId, UserId, Content) values (92, 25, 'Reiter arthritis-pelvis');
insert into EventComments (EventId, UserId, Content) values (39, 49, 'W/crf stair fall-per NOS');
insert into EventComments (EventId, UserId, Content) values (68, 51, 'Parapoxvirus infectn NEC');
insert into EventComments (EventId, UserId, Content) values (65, 66, 'Yellow fever NOS');
insert into EventComments (EventId, UserId, Content) values (59, 99, 'Martial arts');
insert into EventComments (EventId, UserId, Content) values (67, 13, 'Pois-parasympatholytics');
insert into EventComments (EventId, UserId, Content) values (94, 17, 'Choledochlith/ac gb-obst');
insert into EventComments (EventId, UserId, Content) values (100, 97, 'Malign neopl orbit');
insert into EventComments (EventId, UserId, Content) values (34, 76, 'Open wnd mouth NOS-compl');
insert into EventComments (EventId, UserId, Content) values (22, 52, 'Fall from skateboard');
insert into EventComments (EventId, UserId, Content) values (25, 59, 'Opn wound neck NEC-compl');
insert into EventComments (EventId, UserId, Content) values (50, 47, 'Mal neo transverse colon');
insert into EventComments (EventId, UserId, Content) values (11, 80, 'Opn skl base fx-mod coma');
insert into EventComments (EventId, UserId, Content) values (72, 84, 'Eosinophilia');
insert into EventComments (EventId, UserId, Content) values (41, 8, 'Open wound pharynx-compl');
insert into EventComments (EventId, UserId, Content) values (88, 85, 'Fertility testing');
insert into EventComments (EventId, UserId, Content) values (75, 23, 'Mv coll w pedest-st car');
insert into EventComments (EventId, UserId, Content) values (42, 40, 'Otorrhea NOS');
insert into EventComments (EventId, UserId, Content) values (48, 69, 'TB pneumonia-no exam');
insert into EventComments (EventId, UserId, Content) values (8, 78, 'TB bone/jt NOS-oth test');
insert into EventComments (EventId, UserId, Content) values (31, 15, 'Locked-in state');
insert into EventComments (EventId, UserId, Content) values (3, 49, 'Fail induct NOS-antepart');
insert into EventComments (EventId, UserId, Content) values (86, 94, 'Post tp lymphprolif dis');
insert into EventComments (EventId, UserId, Content) values (22, 14, 'Edwards'' syndrome');
insert into EventComments (EventId, UserId, Content) values (83, 12, 'Acc pois-solid/liq NOS');
insert into EventComments (EventId, UserId, Content) values (5, 87, 'Prsc ntrutr cntrcptv dvc');
insert into EventComments (EventId, UserId, Content) values (21, 51, 'Ac/chr syst/dia hrt fail');
insert into EventComments (EventId, UserId, Content) values (93, 28, 'Presenile delusion');
insert into EventComments (EventId, UserId, Content) values (68, 78, 'Toxic effect metals NEC');
insert into EventComments (EventId, UserId, Content) values (33, 70, 'Mycosis fungoides axilla');
insert into EventComments (EventId, UserId, Content) values (68, 24, 'Fat embolism');
insert into EventComments (EventId, UserId, Content) values (7, 8, 'Injury ovarian artery');
insert into EventComments (EventId, UserId, Content) values (53, 13, 'Unc behav neo adrenal');
insert into EventComments (EventId, UserId, Content) values (4, 4, 'Del w 2 deg lacerat-del');
insert into EventComments (EventId, UserId, Content) values (16, 57, 'Lt-date w/mal 1500-1749g');
insert into EventComments (EventId, UserId, Content) values (90, 15, 'Spina bifida-lumbar');
insert into EventComments (EventId, UserId, Content) values (79, 50, 'Septal closure anom NEC');
insert into EventComments (EventId, UserId, Content) values (96, 13, 'Abnormal posture');
insert into EventComments (EventId, UserId, Content) values (86, 46, 'Mood disorder other dis');
insert into EventComments (EventId, UserId, Content) values (20, 63, 'Puerp pyrexia-del w p/p');
insert into EventComments (EventId, UserId, Content) values (99, 16, 'IV bisphosphonates');
insert into EventComments (EventId, UserId, Content) values (93, 89, 'Herpes zoster NOS');
insert into EventComments (EventId, UserId, Content) values (92, 76, 'Hypercementosis');
insert into EventComments (EventId, UserId, Content) values (33, 43, 'Pigment epitheliopathy');
insert into EventComments (EventId, UserId, Content) values (32, 41, 'Cervical agenesis');
insert into EventComments (EventId, UserId, Content) values (4, 2, 'Changes in skin texture');
insert into EventComments (EventId, UserId, Content) values (46, 73, 'Trichiasis w/o entropion');
insert into EventComments (EventId, UserId, Content) values (18, 18, 'Acc poison-glutethimide');
insert into EventComments (EventId, UserId, Content) values (81, 67, 'Housing/econo circum NOS');
insert into EventComments (EventId, UserId, Content) values (94, 59, 'Hyp ht/kd NOS st V w hf');
insert into EventComments (EventId, UserId, Content) values (98, 69, 'Oligohydramnios aff NB');
insert into EventComments (EventId, UserId, Content) values (90, 37, 'Hx Methicln resist Staph');
insert into EventComments (EventId, UserId, Content) values (76, 54, 'Liveborn NOS-nonhosp');
insert into EventComments (EventId, UserId, Content) values (83, 71, 'Abn plac NEC/NOS aff NB');
insert into EventComments (EventId, UserId, Content) values (86, 62, 'Condctv hear loss, bilat');
insert into EventComments (EventId, UserId, Content) values (21, 57, 'Cl skull vlt fx-coma NOS');
insert into EventComments (EventId, UserId, Content) values (35, 94, 'Aseptic necrosis humerus');
insert into EventComments (EventId, UserId, Content) values (98, 98, 'Pulmon circulat dis NOS');
insert into EventComments (EventId, UserId, Content) values (71, 15, 'Animal drawn veh-occupan');
insert into EventComments (EventId, UserId, Content) values (20, 29, '80-89% bdy brn/40-49% 3d');
insert into EventComments (EventId, UserId, Content) values (98, 17, 'Wtrcraft fall NEC-docker');
insert into EventComments (EventId, UserId, Content) values (52, 11, 'Septic shock');
insert into EventComments (EventId, UserId, Content) values (63, 8, 'Reduction deform leg NOS');
insert into EventComments (EventId, UserId, Content) values (15, 11, 'Adjustmnt dis w depressn');
insert into EventComments (EventId, UserId, Content) values (56, 45, 'Lactation fail-delivered');
insert into EventComments (EventId, UserId, Content) values (37, 42, 'Pterygium NOS');
insert into EventComments (EventId, UserId, Content) values (56, 88, 'Mitr/aortic mult involv');
insert into EventComments (EventId, UserId, Content) values (95, 78, 'Malaria complicated NEC');
insert into EventComments (EventId, UserId, Content) values (43, 67, 'Uterine tumor-del w p/p');
insert into EventComments (EventId, UserId, Content) values (13, 5, 'Anesth compl-postpartum');
insert into EventComments (EventId, UserId, Content) values (70, 46, 'Poisoning-enzymes NEC');
insert into EventComments (EventId, UserId, Content) values (84, 44, 'Dis of gallbladder NEC');
insert into EventComments (EventId, UserId, Content) values (73, 83, 'Nervous system anom NOS');
insert into EventComments (EventId, UserId, Content) values (59, 11, 'Peptic ulcer NOS');
insert into EventComments (EventId, UserId, Content) values (71, 99, 'Contaminated drug NEC');
insert into EventComments (EventId, UserId, Content) values (49, 77, 'Hemarthrosis-jt NEC');
insert into EventComments (EventId, UserId, Content) values (60, 98, '3rd deg burn wrist');
insert into EventComments (EventId, UserId, Content) values (91, 42, 'Adv eff corticosteroids');
insert into EventComments (EventId, UserId, Content) values (13, 93, 'Prem rupt memb-antepart');
insert into EventComments (EventId, UserId, Content) values (79, 44, 'Open wound vagina-compl');
insert into EventComments (EventId, UserId, Content) values (23, 73, 'Rheum pulmon valve dis');
insert into EventComments (EventId, UserId, Content) values (54, 31, 'Benign neo skin arm');
insert into EventComments (EventId, UserId, Content) values (69, 81, 'Metastat dissem retinit');
insert into EventComments (EventId, UserId, Content) values (47, 90, 'Iris/ciliary dis NOS');
insert into EventComments (EventId, UserId, Content) values (88, 46, 'Int thrombos hemorrhoid');
COMMIT;
