name: Java CI/CD Pipeline

# Trigger the workflow on push and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that run the pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    # Set the steps for building the Java project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java (specify your Java version)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache the Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Run Maven commands
      - name: Build with Maven
        run: mvn clean install

      # Run Maven tests
      - name: Run tests
        run: mvn test
